### ISSUE TITLE
linterがうまく動いてない

### ISSUE THREAD

**Issue by haiiro2gou** [The-Chicken-Empire/EliteMobs#24]
1.19.4の言語ファイルが存在してない疑惑アリ
1.20を待つか1.19.2に戻るか

**Comment by rukky321** [comment]
rideコマンドとdamageコマンド使いたいから1.19.2に戻すのは無理かな
1.20を待つしかなさそう

**Comment by haiiro2gou** [comment]
1.19.4段階では/damageが正常に検査されない
1.20段階では動作すらしない

**Comment by haiiro2gou** [comment]
linter公式のアプデで1.20対応 ([ここ](https://github.com/ChenCMD/datapack-linter/releases/v1.3.14))
/damageには対応を確認したものの ([ここ](https://github.com/The-Chicken-Empire/EliteMobs/actions/runs/5304533346))
interactionのnbtは拾ってくれてないですね (#32)

**Comment by haiiro2gou** [comment]
mc-nbtdocの更新が遅めなのが原因
datapack-linter v2になって幾分か改善したものの、いまだにnbtdocが古いので正常に検知してくれなさそう

**Comment by haiiro2gou** [comment]
問題はここで論じるべきではなさそう
